"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import QUIKgRPC.Python.grpc.structures_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CallbackRequest(google.protobuf.message.Message):
    """Подписка / Отмена подписки на функции обратного вызова"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FIRM_FIELD_NUMBER: builtins.int
    ALL_TRADE_FIELD_NUMBER: builtins.int
    TRADE_FIELD_NUMBER: builtins.int
    ORDER_FIELD_NUMBER: builtins.int
    ACCOUNT_BALANCE_FIELD_NUMBER: builtins.int
    FUTURES_LIMIT_CHANGE_FIELD_NUMBER: builtins.int
    FUTURES_LIMIT_DELETE_FIELD_NUMBER: builtins.int
    FUTURES_CLIENT_HOLDING_FIELD_NUMBER: builtins.int
    MONEY_LIMIT_FIELD_NUMBER: builtins.int
    MONEY_LIMIT_DELETE_FIELD_NUMBER: builtins.int
    DEPO_LIMIT_FIELD_NUMBER: builtins.int
    DEPO_LIMIT_DELETE_FIELD_NUMBER: builtins.int
    ACCOUNT_POSITION_FIELD_NUMBER: builtins.int
    STOP_ORDER_FIELD_NUMBER: builtins.int
    TRANS_REPLY_FIELD_NUMBER: builtins.int
    PARAM_FIELD_NUMBER: builtins.int
    QUOTE_FIELD_NUMBER: builtins.int
    DISCONNECTED_FIELD_NUMBER: builtins.int
    CONNECTED_FIELD_NUMBER: builtins.int
    CLOSE_FIELD_NUMBER: builtins.int
    STOP_FIELD_NUMBER: builtins.int
    INIT_FIELD_NUMBER: builtins.int
    CANDLE_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    firm: builtins.bool
    """2.2.1 OnFirm Новая фирма"""
    trade: builtins.bool
    """2.2.3 OnTrade Новая сделка / Изменение существующей сделки"""
    order: builtins.bool
    """2.2.4 OnOrder Новая заявка / Изменение существующей заявки"""
    account_balance: builtins.bool
    """2.2.5 OnAccountBalance Изменение текущей позиции по счету"""
    futures_limit_change: builtins.bool
    """2.2.6 OnFuturesLimitChange Изменение ограничений по срочному рынку"""
    futures_limit_delete: builtins.bool
    """2.2.7 OnFuturesLimitDelete Удаление ограничений по срочному рынку"""
    futures_client_holding: builtins.bool
    """2.2.8 OnFuturesClientHolding Изменение позиции по срочному рынку"""
    money_limit: builtins.bool
    """2.2.9 OnMoneyLimit Изменение денежной позиции"""
    money_limit_delete: builtins.bool
    """2.2.10 OnMoneyLimitDelete Удаление денежной позиции"""
    depo_limit: builtins.bool
    """2.2.11 OnDepoLimit Изменение позиций по инструментам"""
    depo_limit_delete: builtins.bool
    """2.2.12 OnDepoLimitDelete Удаление позиции по инструментам"""
    account_position: builtins.bool
    """2.2.13 OnAccountPosition Изменение денежных средств"""
    stop_order: builtins.bool
    """2.2.14 (OnNegDeal) Новая внебиржевая заявка / Изменение существующей внебиржевой заявки
    2.2.15 (OnNegTrade) Новая внебиржевая сделка / Изменение существующей внебиржевой сделки

    2.2.16 OnStopOrder Новая стоп заявка / Изменение существующей стоп заявки
    """
    trans_reply: builtins.bool
    """2.2.17 OnTransReply Ответ на транзакцию пользователя"""
    param: builtins.bool
    """2.2.18 OnParam Изменение текущих параметров"""
    disconnected: builtins.bool
    """2.2.20 OnDisconnected Отключение терминала от сервера QUIK"""
    connected: builtins.bool
    """2.2.21 OnConnected Соединение терминала с сервером QUIK"""
    close: builtins.bool
    """2.2.22 (OnCleanUp) Смена сервера QUIK / Пользователя / Сессии

    2.2.23 OnClose Закрытие терминала QUIK
    """
    stop: builtins.bool
    """2.2.24 OnStop Остановка LUA скрипта в терминале QUIK / закрытие терминала QUIK"""
    init: builtins.bool
    """2.2.25 OnInit Запуск LUA скрипта в терминале QUIK"""
    error: builtins.bool
    """QUIK# lua_error Сообщение об ошибке"""
    @property
    def all_trade(self) -> global___ClassSecCodeSubscribtion:
        """2.2.2 OnAllTrade Новая обезличенная сделка"""

    @property
    def quote(self) -> global___ClassSecCodeSubscribtion:
        """3.17.1 Subscribe_Level_II_Quotes Функция заказывает на сервер получение стакана по указанному режиму торгов и инструменту
        3.17.2 Unsubscribe_Level_II_Quotes Функция отменяет заказ на получение с сервера стакана по указанному режиму торгов и инструменту
        2.2.19 OnQuote Изменение стакана котировок
        """

    @property
    def candle(self) -> global___CandleSubscribtion:
        """2.2.26 (main) Функция, реализующая основной поток выполнения в скрипте

        QUIK# subscribe_to_candles Подписка на свечи
        QUIK# unsubscribe_from_candles Отмена подписки на свечи
        QUIK# NewCandle Новая свечка
        """

    def __init__(
        self,
        *,
        firm: builtins.bool = ...,
        all_trade: global___ClassSecCodeSubscribtion | None = ...,
        trade: builtins.bool = ...,
        order: builtins.bool = ...,
        account_balance: builtins.bool = ...,
        futures_limit_change: builtins.bool = ...,
        futures_limit_delete: builtins.bool = ...,
        futures_client_holding: builtins.bool = ...,
        money_limit: builtins.bool = ...,
        money_limit_delete: builtins.bool = ...,
        depo_limit: builtins.bool = ...,
        depo_limit_delete: builtins.bool = ...,
        account_position: builtins.bool = ...,
        stop_order: builtins.bool = ...,
        trans_reply: builtins.bool = ...,
        param: builtins.bool = ...,
        quote: global___ClassSecCodeSubscribtion | None = ...,
        disconnected: builtins.bool = ...,
        connected: builtins.bool = ...,
        close: builtins.bool = ...,
        stop: builtins.bool = ...,
        init: builtins.bool = ...,
        candle: global___CandleSubscribtion | None = ...,
        error: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["account_balance", b"account_balance", "account_position", b"account_position", "all_trade", b"all_trade", "candle", b"candle", "close", b"close", "connected", b"connected", "depo_limit", b"depo_limit", "depo_limit_delete", b"depo_limit_delete", "disconnected", b"disconnected", "error", b"error", "firm", b"firm", "futures_client_holding", b"futures_client_holding", "futures_limit_change", b"futures_limit_change", "futures_limit_delete", b"futures_limit_delete", "init", b"init", "money_limit", b"money_limit", "money_limit_delete", b"money_limit_delete", "order", b"order", "param", b"param", "payload", b"payload", "quote", b"quote", "stop", b"stop", "stop_order", b"stop_order", "trade", b"trade", "trans_reply", b"trans_reply"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["account_balance", b"account_balance", "account_position", b"account_position", "all_trade", b"all_trade", "candle", b"candle", "close", b"close", "connected", b"connected", "depo_limit", b"depo_limit", "depo_limit_delete", b"depo_limit_delete", "disconnected", b"disconnected", "error", b"error", "firm", b"firm", "futures_client_holding", b"futures_client_holding", "futures_limit_change", b"futures_limit_change", "futures_limit_delete", b"futures_limit_delete", "init", b"init", "money_limit", b"money_limit", "money_limit_delete", b"money_limit_delete", "order", b"order", "param", b"param", "payload", b"payload", "quote", b"quote", "stop", b"stop", "stop_order", b"stop_order", "trade", b"trade", "trans_reply", b"trans_reply"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["payload", b"payload"]) -> typing.Literal["firm", "all_trade", "trade", "order", "account_balance", "futures_limit_change", "futures_limit_delete", "futures_client_holding", "money_limit", "money_limit_delete", "depo_limit", "depo_limit_delete", "account_position", "stop_order", "trans_reply", "param", "quote", "disconnected", "connected", "close", "stop", "init", "candle", "error"] | None: ...

global___CallbackRequest = CallbackRequest

@typing.final
class ClassSecCodeSubscribtion(google.protobuf.message.Message):
    """Запросы Подписки / Отмены подписки

    Режим торгов и инструмент
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLASS_SEC_CODE_FIELD_NUMBER: builtins.int
    SUBSCRIBE_FIELD_NUMBER: builtins.int
    subscribe: builtins.bool
    """True - Подписка, False - Отмена подписки"""
    @property
    def class_sec_code(self) -> QUIKgRPC.Python.grpc.structures_pb2.ClassSecCode:
        """Режим торгов и инструмент"""

    def __init__(
        self,
        *,
        class_sec_code: QUIKgRPC.Python.grpc.structures_pb2.ClassSecCode | None = ...,
        subscribe: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["class_sec_code", b"class_sec_code"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["class_sec_code", b"class_sec_code", "subscribe", b"subscribe"]) -> None: ...

global___ClassSecCodeSubscribtion = ClassSecCodeSubscribtion

@typing.final
class CandleSubscribtion(google.protobuf.message.Message):
    """Новые свечки"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLASS_SEC_CODE_FIELD_NUMBER: builtins.int
    TIMEFRAME_FIELD_NUMBER: builtins.int
    PARAM_FIELD_NUMBER: builtins.int
    SUBSCRIBE_FIELD_NUMBER: builtins.int
    timeframe: QUIKgRPC.Python.grpc.structures_pb2.TimeFrame.ValueType
    """Временной интервал"""
    param: builtins.str
    """Если параметр не задан, то заказываются данные на основании Таблицы обезличенных сделок, если задан – данные по этому параметру https://forum.quik.ru/forum10/topic7249/"""
    subscribe: builtins.bool
    """True - Подписка, False - Отмена подписки"""
    @property
    def class_sec_code(self) -> QUIKgRPC.Python.grpc.structures_pb2.ClassSecCode:
        """Режим торгов и инструмент"""

    def __init__(
        self,
        *,
        class_sec_code: QUIKgRPC.Python.grpc.structures_pb2.ClassSecCode | None = ...,
        timeframe: QUIKgRPC.Python.grpc.structures_pb2.TimeFrame.ValueType = ...,
        param: builtins.str | None = ...,
        subscribe: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_param", b"_param", "class_sec_code", b"class_sec_code", "param", b"param"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_param", b"_param", "class_sec_code", b"class_sec_code", "param", b"param", "subscribe", b"subscribe", "timeframe", b"timeframe"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_param", b"_param"]) -> typing.Literal["param"] | None: ...

global___CandleSubscribtion = CandleSubscribtion

@typing.final
class CallbackResponse(google.protobuf.message.Message):
    """Сообщения обратного вызова"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FIRM_FIELD_NUMBER: builtins.int
    ALL_TRADE_FIELD_NUMBER: builtins.int
    TRADE_FIELD_NUMBER: builtins.int
    ORDER_FIELD_NUMBER: builtins.int
    ACCOUNT_BALANCE_FIELD_NUMBER: builtins.int
    FUTURES_LIMIT_CHANGE_FIELD_NUMBER: builtins.int
    FUTURES_LIMIT_DELETE_FIELD_NUMBER: builtins.int
    FUTURES_CLIENT_HOLDING_FIELD_NUMBER: builtins.int
    MONEY_LIMIT_FIELD_NUMBER: builtins.int
    MONEY_LIMIT_DELETE_FIELD_NUMBER: builtins.int
    DEPO_LIMIT_FIELD_NUMBER: builtins.int
    DEPO_LIMIT_DELETE_FIELD_NUMBER: builtins.int
    ACCOUNT_POSITION_FIELD_NUMBER: builtins.int
    STOP_ORDER_FIELD_NUMBER: builtins.int
    TRANS_REPLY_FIELD_NUMBER: builtins.int
    PARAM_FIELD_NUMBER: builtins.int
    QUOTE_FIELD_NUMBER: builtins.int
    DISCONNECTED_FIELD_NUMBER: builtins.int
    CONNECTED_FIELD_NUMBER: builtins.int
    CLOSE_FIELD_NUMBER: builtins.int
    STOP_FIELD_NUMBER: builtins.int
    INIT_FIELD_NUMBER: builtins.int
    CANDLE_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    disconnected: builtins.bool
    """2.2.20 OnDisconnected Функция вызывается терминалом QUIK при отключении от сервера QUIK"""
    connected: builtins.bool
    """2.2.21 OnConnected Функция вызывается терминалом QUIK при установлении связи с сервером QUIK и получении терминалом описания хотя бы одного режима торгов."""
    @property
    def firm(self) -> QUIKgRPC.Python.grpc.structures_pb2.Firm:
        """2.2.1 OnFirm Функция вызывается терминалом QUIK при получении описания новой фирмы от сервера"""

    @property
    def all_trade(self) -> QUIKgRPC.Python.grpc.structures_pb2.AllTrade:
        """2.2.2 OnAllTrade Функция вызывается терминалом QUIK при получении обезличенной сделки"""

    @property
    def trade(self) -> QUIKgRPC.Python.grpc.structures_pb2.Trade:
        """2.2.3 OnTrade Функция вызывается терминалом QUIK при получении сделки или при изменении параметров существующей сделки"""

    @property
    def order(self) -> QUIKgRPC.Python.grpc.structures_pb2.Order:
        """2.2.4 OnOrder Функция вызывается терминалом QUIK при получении новой заявки или при изменении параметров существующей заявки"""

    @property
    def account_balance(self) -> QUIKgRPC.Python.grpc.structures_pb2.AccountBalance:
        """2.2.5 OnAccountBalance Функция вызывается терминалом QUIK при получении изменений текущей позиции по счету"""

    @property
    def futures_limit_change(self) -> QUIKgRPC.Python.grpc.structures_pb2.FuturesLimit:
        """2.2.6 OnFuturesLimitChange Функция вызывается терминалом QUIK при получении изменений ограничений по срочному рынку"""

    @property
    def futures_limit_delete(self) -> QUIKgRPC.Python.grpc.structures_pb2.FuturesLimitDelete:
        """2.2.7 OnFuturesLimitDelete Функция вызывается терминалом QUIK при удалении лимита по срочному рынку"""

    @property
    def futures_client_holding(self) -> QUIKgRPC.Python.grpc.structures_pb2.FuturesClientHolding:
        """2.2.8 OnFuturesClientHolding Функция вызывается терминалом QUIK при изменении позиции по срочному рынку"""

    @property
    def money_limit(self) -> QUIKgRPC.Python.grpc.structures_pb2.MoneyLimit:
        """2.2.9 OnMoneyLimit Функция вызывается терминалом QUIK при получении изменений по денежной позиции клиента"""

    @property
    def money_limit_delete(self) -> QUIKgRPC.Python.grpc.structures_pb2.MoneyLimitDelete:
        """2.2.10 OnMoneyLimitDelete Функция вызывается терминалом QUIK при удалении денежной позиции"""

    @property
    def depo_limit(self) -> QUIKgRPC.Python.grpc.structures_pb2.DepoLimit:
        """2.2.11 OnDepoLimit Функция вызывается терминалом QUIK при получении изменений позиции по инструментам"""

    @property
    def depo_limit_delete(self) -> QUIKgRPC.Python.grpc.structures_pb2.DepoLimitDelete:
        """2.2.12 OnDepoLimitDelete Функция вызывается терминалом QUIK при удалении позиции клиента по инструментам"""

    @property
    def account_position(self) -> QUIKgRPC.Python.grpc.structures_pb2.AccountPosition:
        """2.2.13 OnAccountPosition Функция вызывается терминалом QUIK при изменении позиции участника по денежным средствам"""

    @property
    def stop_order(self) -> QUIKgRPC.Python.grpc.structures_pb2.StopOrder:
        """2.2.14 (OnNegDeal) Функция вызывается терминалом QUIK при получении внебиржевой заявки или при изменении параметров существующей внебиржевой заявки
        2.2.15 (OnNegTrade) Функция вызывается терминалом QUIK при получении сделки для исполнения или при изменении параметров существующей сделки для исполнения

        2.2.16 OnStopOrder Функция вызывается терминалом QUIK при получении новой стоп-заявки или при изменении параметров существующей стоп-заявки
        """

    @property
    def trans_reply(self) -> QUIKgRPC.Python.grpc.structures_pb2.TransReply:
        """2.2.17 OnTransReply Функция вызывается терминалом QUIK при получении ответа на транзакцию пользователя,
        отправленную с помощью любого плагина Рабочего места QUIK (в том числе QLua). Для транзакций,
        отправленных с помощью Trans2quik.dll, QPILE или динамической загрузки транзакций из файла, функция не вызывается
        """

    @property
    def param(self) -> QUIKgRPC.Python.grpc.structures_pb2.ClassSecCode:
        """2.2.18 OnParam Функция вызывается терминалом QUIK при изменении текущих параметров"""

    @property
    def quote(self) -> QUIKgRPC.Python.grpc.structures_pb2.Quote:
        """2.2.19 OnQuote Функция вызывается терминалом QUIK при получении изменения стакана котировок"""

    @property
    def close(self) -> QUIKgRPC.Python.grpc.structures_pb2.Empty:
        """2.2.22 (OnCleanUp) Функция вызывается терминалом QUIK в следующих случаях: смена сервера QUIK внутри торговой сессии; смена пользователя, которым выполняется подключение к серверу QUIK, внутри торговой сессии; смена сессии

        2.2.23 OnClose Функция вызывается перед закрытием терминала QUIK и при выгрузке файла qlua.dll
        """

    @property
    def stop(self) -> QUIKgRPC.Python.grpc.structures_pb2.QuikInt:
        """2.2.24 OnStop Функция вызывается терминалом QUIK при остановке скрипта из диалога управления и при закрытии терминала QUIK. Параметр вызова (и ответа) flag принимает значения:
        1 - При остановке или удалении работающего скрипта Lua из диалога управления Доступные скрипты; 2 - При закрытии терминала QUIK
        """

    @property
    def init(self) -> QUIKgRPC.Python.grpc.structures_pb2.QuikString:
        """2.2.25 OnInit Функция вызывается терминалом QUIK перед вызовом функции main(). В качестве параметра принимает значение полного пути к запускаемому скрипту"""

    @property
    def candle(self) -> QUIKgRPC.Python.grpc.structures_pb2.Candle:
        """2.2.26 (main) Функция, реализующая основной поток выполнения в скрипте. Для ее выполнения терминал QUIK создает отдельный поток.
        Скрипт считается работающим, пока работает функция Руководство пользователя Интерпретатора языка Lua 21 main().
        При завершении работы функции main() скрипт переходит в состояние «остановлен».
        Если скрипт находится в состоянии «остановлен», то не происходит вызовов функций обработки событий терминала QUIK, содержащихся в этом скрипте

        QUIK# NewCandle Новая свечка
        """

    @property
    def error(self) -> QUIKgRPC.Python.grpc.structures_pb2.QuikString:
        """QUIK# lua_error Сообщение об ошибке при подписке/запросе стакана"""

    def __init__(
        self,
        *,
        firm: QUIKgRPC.Python.grpc.structures_pb2.Firm | None = ...,
        all_trade: QUIKgRPC.Python.grpc.structures_pb2.AllTrade | None = ...,
        trade: QUIKgRPC.Python.grpc.structures_pb2.Trade | None = ...,
        order: QUIKgRPC.Python.grpc.structures_pb2.Order | None = ...,
        account_balance: QUIKgRPC.Python.grpc.structures_pb2.AccountBalance | None = ...,
        futures_limit_change: QUIKgRPC.Python.grpc.structures_pb2.FuturesLimit | None = ...,
        futures_limit_delete: QUIKgRPC.Python.grpc.structures_pb2.FuturesLimitDelete | None = ...,
        futures_client_holding: QUIKgRPC.Python.grpc.structures_pb2.FuturesClientHolding | None = ...,
        money_limit: QUIKgRPC.Python.grpc.structures_pb2.MoneyLimit | None = ...,
        money_limit_delete: QUIKgRPC.Python.grpc.structures_pb2.MoneyLimitDelete | None = ...,
        depo_limit: QUIKgRPC.Python.grpc.structures_pb2.DepoLimit | None = ...,
        depo_limit_delete: QUIKgRPC.Python.grpc.structures_pb2.DepoLimitDelete | None = ...,
        account_position: QUIKgRPC.Python.grpc.structures_pb2.AccountPosition | None = ...,
        stop_order: QUIKgRPC.Python.grpc.structures_pb2.StopOrder | None = ...,
        trans_reply: QUIKgRPC.Python.grpc.structures_pb2.TransReply | None = ...,
        param: QUIKgRPC.Python.grpc.structures_pb2.ClassSecCode | None = ...,
        quote: QUIKgRPC.Python.grpc.structures_pb2.Quote | None = ...,
        disconnected: builtins.bool = ...,
        connected: builtins.bool = ...,
        close: QUIKgRPC.Python.grpc.structures_pb2.Empty | None = ...,
        stop: QUIKgRPC.Python.grpc.structures_pb2.QuikInt | None = ...,
        init: QUIKgRPC.Python.grpc.structures_pb2.QuikString | None = ...,
        candle: QUIKgRPC.Python.grpc.structures_pb2.Candle | None = ...,
        error: QUIKgRPC.Python.grpc.structures_pb2.QuikString | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["account_balance", b"account_balance", "account_position", b"account_position", "all_trade", b"all_trade", "candle", b"candle", "close", b"close", "connected", b"connected", "depo_limit", b"depo_limit", "depo_limit_delete", b"depo_limit_delete", "disconnected", b"disconnected", "error", b"error", "firm", b"firm", "futures_client_holding", b"futures_client_holding", "futures_limit_change", b"futures_limit_change", "futures_limit_delete", b"futures_limit_delete", "init", b"init", "money_limit", b"money_limit", "money_limit_delete", b"money_limit_delete", "order", b"order", "param", b"param", "payload", b"payload", "quote", b"quote", "stop", b"stop", "stop_order", b"stop_order", "trade", b"trade", "trans_reply", b"trans_reply"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["account_balance", b"account_balance", "account_position", b"account_position", "all_trade", b"all_trade", "candle", b"candle", "close", b"close", "connected", b"connected", "depo_limit", b"depo_limit", "depo_limit_delete", b"depo_limit_delete", "disconnected", b"disconnected", "error", b"error", "firm", b"firm", "futures_client_holding", b"futures_client_holding", "futures_limit_change", b"futures_limit_change", "futures_limit_delete", b"futures_limit_delete", "init", b"init", "money_limit", b"money_limit", "money_limit_delete", b"money_limit_delete", "order", b"order", "param", b"param", "payload", b"payload", "quote", b"quote", "stop", b"stop", "stop_order", b"stop_order", "trade", b"trade", "trans_reply", b"trans_reply"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["payload", b"payload"]) -> typing.Literal["firm", "all_trade", "trade", "order", "account_balance", "futures_limit_change", "futures_limit_delete", "futures_client_holding", "money_limit", "money_limit_delete", "depo_limit", "depo_limit_delete", "account_position", "stop_order", "trans_reply", "param", "quote", "disconnected", "connected", "close", "stop", "init", "candle", "error"] | None: ...

global___CallbackResponse = CallbackResponse
