# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from QUIKgRPC.Python.grpc import service_pb2 as QUIKgRPC_dot_Python_dot_grpc_dot_service__pb2
from QUIKgRPC.Python.grpc import structures_pb2 as QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in QUIKgRPC/Python/grpc/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServiceFunctionsStub(object):
    """Функции отладки / Сервисные функции
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/functions.ServiceFunctions/Ping',
                request_serializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikString.SerializeToString,
                response_deserializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikString.FromString,
                _registered_method=True)
        self.Echo = channel.unary_unary(
                '/functions.ServiceFunctions/Echo',
                request_serializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikString.SerializeToString,
                response_deserializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikString.FromString,
                _registered_method=True)
        self.DivideStringByZero = channel.unary_unary(
                '/functions.ServiceFunctions/DivideStringByZero',
                request_serializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.Empty.SerializeToString,
                response_deserializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.Empty.FromString,
                _registered_method=True)
        self.IsQuik = channel.unary_unary(
                '/functions.ServiceFunctions/IsQuik',
                request_serializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.Empty.SerializeToString,
                response_deserializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikBool.FromString,
                _registered_method=True)
        self.IsConnected = channel.unary_unary(
                '/functions.ServiceFunctions/IsConnected',
                request_serializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.Empty.SerializeToString,
                response_deserializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikBool.FromString,
                _registered_method=True)
        self.GetScriptPath = channel.unary_unary(
                '/functions.ServiceFunctions/GetScriptPath',
                request_serializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.Empty.SerializeToString,
                response_deserializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikString.FromString,
                _registered_method=True)
        self.GetInfoParam = channel.unary_unary(
                '/functions.ServiceFunctions/GetInfoParam',
                request_serializer=QUIKgRPC_dot_Python_dot_grpc_dot_service__pb2.InfoParamRequest.SerializeToString,
                response_deserializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikString.FromString,
                _registered_method=True)
        self.Message = channel.unary_unary(
                '/functions.ServiceFunctions/Message',
                request_serializer=QUIKgRPC_dot_Python_dot_grpc_dot_service__pb2.MessageRequest.SerializeToString,
                response_deserializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.Empty.FromString,
                _registered_method=True)
        self.Sleep = channel.unary_unary(
                '/functions.ServiceFunctions/Sleep',
                request_serializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikInt.SerializeToString,
                response_deserializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.Empty.FromString,
                _registered_method=True)
        self.GetWorkingFolder = channel.unary_unary(
                '/functions.ServiceFunctions/GetWorkingFolder',
                request_serializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.Empty.SerializeToString,
                response_deserializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikString.FromString,
                _registered_method=True)
        self.PrintDbgStr = channel.unary_unary(
                '/functions.ServiceFunctions/PrintDbgStr',
                request_serializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikString.SerializeToString,
                response_deserializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.Empty.FromString,
                _registered_method=True)


class ServiceFunctionsServicer(object):
    """Функции отладки / Сервисные функции
    """

    def Ping(self, request, context):
        """QUIK# Отправка строки ping. Получение строки pong
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Echo(self, request, context):
        """QUIK# Отправка и получение одного и того же сообщения (эхо)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DivideStringByZero(self, request, context):
        """QUIK# Тест обработки ошибок. Выполняется деление строки на 0
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsQuik(self, request, context):
        """QUIK# Скрипт запущен в QUIK
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsConnected(self, request, context):
        """2.1.1 Функция предназначена для определения состояния подключения клиентского места к серверу
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScriptPath(self, request, context):
        """2.1.2 Функция возвращает путь, по которому находится запускаемый скрипт, без завершающего обратного слеша (\). Например, C:\QuikFront\Scripts 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInfoParam(self, request, context):
        """2.1.3 Функция возвращает значения параметров информационного окна (пункт меню Система / О программе / Информационное окно…)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Message(self, request, context):
        """2.1.4 Функция отображает сообщения в терминале QUIK
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sleep(self, request, context):
        """2.1.5 Функция приостанавливает выполнение скрипта
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkingFolder(self, request, context):
        """2.1.6 Функция возвращает путь, по которому находится файл info.exe, исполняющий данный скрипт, без завершающего обратного слеша (\). Например, c:\QuikFront  
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrintDbgStr(self, request, context):
        """2.1.7 Функция для вывода отладочной информации
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceFunctionsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikString.FromString,
                    response_serializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikString.SerializeToString,
            ),
            'Echo': grpc.unary_unary_rpc_method_handler(
                    servicer.Echo,
                    request_deserializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikString.FromString,
                    response_serializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikString.SerializeToString,
            ),
            'DivideStringByZero': grpc.unary_unary_rpc_method_handler(
                    servicer.DivideStringByZero,
                    request_deserializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.Empty.FromString,
                    response_serializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.Empty.SerializeToString,
            ),
            'IsQuik': grpc.unary_unary_rpc_method_handler(
                    servicer.IsQuik,
                    request_deserializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.Empty.FromString,
                    response_serializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikBool.SerializeToString,
            ),
            'IsConnected': grpc.unary_unary_rpc_method_handler(
                    servicer.IsConnected,
                    request_deserializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.Empty.FromString,
                    response_serializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikBool.SerializeToString,
            ),
            'GetScriptPath': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScriptPath,
                    request_deserializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.Empty.FromString,
                    response_serializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikString.SerializeToString,
            ),
            'GetInfoParam': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfoParam,
                    request_deserializer=QUIKgRPC_dot_Python_dot_grpc_dot_service__pb2.InfoParamRequest.FromString,
                    response_serializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikString.SerializeToString,
            ),
            'Message': grpc.unary_unary_rpc_method_handler(
                    servicer.Message,
                    request_deserializer=QUIKgRPC_dot_Python_dot_grpc_dot_service__pb2.MessageRequest.FromString,
                    response_serializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.Empty.SerializeToString,
            ),
            'Sleep': grpc.unary_unary_rpc_method_handler(
                    servicer.Sleep,
                    request_deserializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikInt.FromString,
                    response_serializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.Empty.SerializeToString,
            ),
            'GetWorkingFolder': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkingFolder,
                    request_deserializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.Empty.FromString,
                    response_serializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikString.SerializeToString,
            ),
            'PrintDbgStr': grpc.unary_unary_rpc_method_handler(
                    servicer.PrintDbgStr,
                    request_deserializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikString.FromString,
                    response_serializer=QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'functions.ServiceFunctions', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('functions.ServiceFunctions', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServiceFunctions(object):
    """Функции отладки / Сервисные функции
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/functions.ServiceFunctions/Ping',
            QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikString.SerializeToString,
            QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikString.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Echo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/functions.ServiceFunctions/Echo',
            QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikString.SerializeToString,
            QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikString.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DivideStringByZero(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/functions.ServiceFunctions/DivideStringByZero',
            QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.Empty.SerializeToString,
            QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsQuik(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/functions.ServiceFunctions/IsQuik',
            QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.Empty.SerializeToString,
            QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikBool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsConnected(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/functions.ServiceFunctions/IsConnected',
            QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.Empty.SerializeToString,
            QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikBool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScriptPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/functions.ServiceFunctions/GetScriptPath',
            QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.Empty.SerializeToString,
            QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikString.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInfoParam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/functions.ServiceFunctions/GetInfoParam',
            QUIKgRPC_dot_Python_dot_grpc_dot_service__pb2.InfoParamRequest.SerializeToString,
            QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikString.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Message(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/functions.ServiceFunctions/Message',
            QUIKgRPC_dot_Python_dot_grpc_dot_service__pb2.MessageRequest.SerializeToString,
            QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sleep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/functions.ServiceFunctions/Sleep',
            QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikInt.SerializeToString,
            QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkingFolder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/functions.ServiceFunctions/GetWorkingFolder',
            QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.Empty.SerializeToString,
            QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikString.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrintDbgStr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/functions.ServiceFunctions/PrintDbgStr',
            QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.QuikString.SerializeToString,
            QUIKgRPC_dot_Python_dot_grpc_dot_structures__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
