"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _InfoParamName:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _InfoParamNameEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_InfoParamName.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    VERSION: _InfoParamName.ValueType  # 0
    """Версия программы"""
    TRADEDATE: _InfoParamName.ValueType  # 1
    """Дата торгов"""
    SERVERTIME: _InfoParamName.ValueType  # 2
    """Время сервера"""
    LASTRECORDTIME: _InfoParamName.ValueType  # 3
    """Время последней записи"""
    NUMRECORDS: _InfoParamName.ValueType  # 4
    """Число записей"""
    LASTRECORD: _InfoParamName.ValueType  # 5
    """Последняя запись"""
    LATERECORD: _InfoParamName.ValueType  # 6
    """Отставшая запись"""
    CONNECTION: _InfoParamName.ValueType  # 7
    """Соединение"""
    IPADDRESS: _InfoParamName.ValueType  # 8
    """IP-адрес сервера"""
    IPPORT: _InfoParamName.ValueType  # 9
    """Порт сервера"""
    IPCOMMENT: _InfoParamName.ValueType  # 10
    """Описание соединения"""
    SERVER: _InfoParamName.ValueType  # 11
    """Описание сервера"""
    SESSIONID: _InfoParamName.ValueType  # 12
    """Идентификатор сессии"""
    USER: _InfoParamName.ValueType  # 13
    """Пользователь"""
    USERID: _InfoParamName.ValueType  # 14
    """ID пользователя"""
    ORG: _InfoParamName.ValueType  # 15
    """Организация"""
    MEMORY: _InfoParamName.ValueType  # 16
    """Занято памяти"""
    LOCALTIME: _InfoParamName.ValueType  # 17
    """Текущее время"""
    CONNECTIONTIME: _InfoParamName.ValueType  # 18
    """Время на связи"""
    MESSAGESSENT: _InfoParamName.ValueType  # 19
    """Передано сообщений"""
    ALLSENT: _InfoParamName.ValueType  # 20
    """Передано всего байт"""
    BYTESSENT: _InfoParamName.ValueType  # 21
    """Передано полезных байт"""
    BYTESPERSECSENT: _InfoParamName.ValueType  # 22
    """Передано за секунду"""
    MESSAGESRECV: _InfoParamName.ValueType  # 23
    """Принято сообщений"""
    BYTESRECV: _InfoParamName.ValueType  # 24
    """Принято полезных байт"""
    ALLRECV: _InfoParamName.ValueType  # 25
    """Принято всего байт"""
    BYTESPERSECRECV: _InfoParamName.ValueType  # 26
    """Принято за секунду"""
    AVGSENT: _InfoParamName.ValueType  # 27
    """Средняя скорость передачи"""
    AVGRECV: _InfoParamName.ValueType  # 28
    """Средняя скорость приема"""
    LASTPINGTIME: _InfoParamName.ValueType  # 29
    """Время последней проверки связи"""
    LASTPINGDURATION: _InfoParamName.ValueType  # 30
    """Задержка данных при обмене с сервером"""
    AVGPINGDURATION: _InfoParamName.ValueType  # 31
    """Средняя задержка данных"""
    MAXPINGTIME: _InfoParamName.ValueType  # 32
    """Время максимальной задержки"""
    MAXPINGDURATION: _InfoParamName.ValueType  # 33
    """Максимальная задержка данных"""

class InfoParamName(_InfoParamName, metaclass=_InfoParamNameEnumTypeWrapper):
    """Параметры информационного окна"""

VERSION: InfoParamName.ValueType  # 0
"""Версия программы"""
TRADEDATE: InfoParamName.ValueType  # 1
"""Дата торгов"""
SERVERTIME: InfoParamName.ValueType  # 2
"""Время сервера"""
LASTRECORDTIME: InfoParamName.ValueType  # 3
"""Время последней записи"""
NUMRECORDS: InfoParamName.ValueType  # 4
"""Число записей"""
LASTRECORD: InfoParamName.ValueType  # 5
"""Последняя запись"""
LATERECORD: InfoParamName.ValueType  # 6
"""Отставшая запись"""
CONNECTION: InfoParamName.ValueType  # 7
"""Соединение"""
IPADDRESS: InfoParamName.ValueType  # 8
"""IP-адрес сервера"""
IPPORT: InfoParamName.ValueType  # 9
"""Порт сервера"""
IPCOMMENT: InfoParamName.ValueType  # 10
"""Описание соединения"""
SERVER: InfoParamName.ValueType  # 11
"""Описание сервера"""
SESSIONID: InfoParamName.ValueType  # 12
"""Идентификатор сессии"""
USER: InfoParamName.ValueType  # 13
"""Пользователь"""
USERID: InfoParamName.ValueType  # 14
"""ID пользователя"""
ORG: InfoParamName.ValueType  # 15
"""Организация"""
MEMORY: InfoParamName.ValueType  # 16
"""Занято памяти"""
LOCALTIME: InfoParamName.ValueType  # 17
"""Текущее время"""
CONNECTIONTIME: InfoParamName.ValueType  # 18
"""Время на связи"""
MESSAGESSENT: InfoParamName.ValueType  # 19
"""Передано сообщений"""
ALLSENT: InfoParamName.ValueType  # 20
"""Передано всего байт"""
BYTESSENT: InfoParamName.ValueType  # 21
"""Передано полезных байт"""
BYTESPERSECSENT: InfoParamName.ValueType  # 22
"""Передано за секунду"""
MESSAGESRECV: InfoParamName.ValueType  # 23
"""Принято сообщений"""
BYTESRECV: InfoParamName.ValueType  # 24
"""Принято полезных байт"""
ALLRECV: InfoParamName.ValueType  # 25
"""Принято всего байт"""
BYTESPERSECRECV: InfoParamName.ValueType  # 26
"""Принято за секунду"""
AVGSENT: InfoParamName.ValueType  # 27
"""Средняя скорость передачи"""
AVGRECV: InfoParamName.ValueType  # 28
"""Средняя скорость приема"""
LASTPINGTIME: InfoParamName.ValueType  # 29
"""Время последней проверки связи"""
LASTPINGDURATION: InfoParamName.ValueType  # 30
"""Задержка данных при обмене с сервером"""
AVGPINGDURATION: InfoParamName.ValueType  # 31
"""Средняя задержка данных"""
MAXPINGTIME: InfoParamName.ValueType  # 32
"""Время максимальной задержки"""
MAXPINGDURATION: InfoParamName.ValueType  # 33
"""Максимальная задержка данных"""
global___InfoParamName = InfoParamName

class _MessageIconType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MessageIconTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MessageIconType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNSPECIFIED: _MessageIconType.ValueType  # 0
    """Неопределенное значение"""
    INFO: _MessageIconType.ValueType  # 1
    """Информация"""
    WARNING: _MessageIconType.ValueType  # 2
    """Предупреждение"""
    ERROR: _MessageIconType.ValueType  # 3
    """Ошибка"""

class MessageIconType(_MessageIconType, metaclass=_MessageIconTypeEnumTypeWrapper):
    """Тип отображаемой иконки в сообщении"""

UNSPECIFIED: MessageIconType.ValueType  # 0
"""Неопределенное значение"""
INFO: MessageIconType.ValueType  # 1
"""Информация"""
WARNING: MessageIconType.ValueType  # 2
"""Предупреждение"""
ERROR: MessageIconType.ValueType  # 3
"""Ошибка"""
global___MessageIconType = MessageIconType

@typing.final
class InfoParamRequest(google.protobuf.message.Message):
    """Запрос параметров информационного окна"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARAM_NAME_FIELD_NUMBER: builtins.int
    param_name: global___InfoParamName.ValueType
    """Параметр информационного окна"""
    def __init__(
        self,
        *,
        param_name: global___InfoParamName.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["param_name", b"param_name"]) -> None: ...

global___InfoParamRequest = InfoParamRequest

@typing.final
class MessageRequest(google.protobuf.message.Message):
    """Запрос параметров сообщения"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    ICON_TYPE_FIELD_NUMBER: builtins.int
    message: builtins.str
    """Строка, отображаемая в окне сообщений терминала QUIK"""
    icon_type: global___MessageIconType.ValueType
    """Тип отображаемой иконки в сообщении"""
    def __init__(
        self,
        *,
        message: builtins.str = ...,
        icon_type: global___MessageIconType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["icon_type", b"icon_type", "message", b"message"]) -> None: ...

global___MessageRequest = MessageRequest
